name: nokhod_news
description: یک خبرخوان پیشرفته برای کانال‌های تلگرامی
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http:
  xml:

  # Local storage
  hive:
  hive_flutter:
  path_provider:

  # State management
  provider:

  # UI
  cached_network_image:
  flutter_html:
  video_player:
  chewie:
  flutter_localizations:
    sdk: flutter
  intl:
  vazir_fonts:       # فونت وزیر
  shamsi_date:       # تبدیل تاریخ شمسی

  # Settings
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true