name: nokhod_news
description: یک خبرخوان پیشرفته با استفاده از API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http:

  # Local storage
  hive:
  hive_flutter:
  path_provider:

  # State management
  provider:

  # UI
  cached_network_image:
  flutter_html:
  video_player:
  chewie:
  flutter_localizations:
    sdk: flutter
  intl:
  shamsi_date:

  # Settings
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  # فونت وزیر (فایل را در assets/fonts/Vazir.ttf قرار دهید)
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf